import I18n from '@/utils/i18n'

export default [{
  name: I18n.t('formula.mathFunc'),
  children: [{
    name: 'ABS',
    intro: I18n.t('formula.abs.intro'),
    usage: I18n.t('formula.abs.usage'),
    example: I18n.t('formula.abs.example')
  }, {
    name: 'AVERAGE',
    intro: I18n.t('formula.average.intro'),
    usage: I18n.t('formula.average.usage'),
    example: I18n.t('formula.average.example')
  }, {
    name: 'CEILING',
    intro: I18n.t('formula.ceiling.intro'),
    usage: I18n.t('formula.ceiling.usage'),
    example: I18n.t('formula.ceiling.example')
  }, {
    name: 'COUNT',
    intro: I18n.t('formula.count.intro'),
    usage: I18n.t('formula.count.usage'),
    example: I18n.t('formula.count.example')
  }, {
    name: 'COUNTIF',
    intro: I18n.t('formula.countif.intro'),
    usage: I18n.t('formula.countif.usage'),
    example: I18n.t('formula.countif.example')
  }, {
    name: 'FIXED',
    intro: I18n.t('formula.fixed.intro'),
    usage: I18n.t('formula.fixed.usage'),
    example: I18n.t('formula.fixed.example')
  }, {
    name: 'FLOOR',
    intro: I18n.t('formula.floor.intro'),
    usage: I18n.t('formula.floor.usage'),
    example: I18n.t('formula.floor.example')
  }, {
    name: 'INT',
    intro: I18n.t('formula.int.intro'),
    usage: I18n.t('formula.int.usage'),
    example: I18n.t('formula.int.example')
  }, {
    name: 'LARGE',
    intro: I18n.t('formula.large.intro'),
    usage: I18n.t('formula.large.usage'),
    example: I18n.t('formula.large.example')
  }, {
    name: 'LOG',
    intro: I18n.t('formula.log.intro'),
    usage: I18n.t('formula.log.usage'),
    example: I18n.t('formula.log.example')
  }, {
    name: 'MAX',
    intro: I18n.t('formula.max.intro'),
    usage: I18n.t('formula.max.usage'),
    example: I18n.t('formula.max.example')
  }, {
    name: 'MIN',
    intro: I18n.t('formula.min.intro'),
    usage: I18n.t('formula.min.usage'),
    example: I18n.t('formula.min.example')
  }, {
    name: 'MOD',
    intro: I18n.t('formula.mod.intro'),
    usage: I18n.t('formula.mod.usage'),
    example: I18n.t('formula.mod.example')
  }, {
    name: 'POWER',
    intro: I18n.t('formula.power.intro'),
    usage: I18n.t('formula.power.usage'),
    example: I18n.t('formula.power.example')
  }, {
    name: 'PRODUCT',
    intro: I18n.t('formula.product.intro'),
    usage: I18n.t('formula.product.usage'),
    example: I18n.t('formula.product.example')
  }, {
    name: 'RAND',
    intro: I18n.t('formula.rand.intro'),
    usage: I18n.t('formula.rand.usage'),
    example: I18n.t('formula.rand.example')
  }, {
    name: 'ROUND',
    intro: I18n.t('formula.round.intro'),
    usage: I18n.t('formula.round.usage'),
    example: I18n.t('formula.round.example')
  }, {
    name: 'SMALL',
    intro: I18n.t('formula.small.intro'),
    usage: I18n.t('formula.small.usage'),
    example: I18n.t('formula.small.example')
  }, {
    name: 'SQRT',
    intro: I18n.t('formula.sqrt.intro'),
    usage: I18n.t('formula.sqrt.usage'),
    example: I18n.t('formula.sqrt.example')
  }, {
    name: 'SUM',
    intro: I18n.t('formula.sum.intro'),
    usage: I18n.t('formula.sum.usage'),
    example: I18n.t('formula.sum.example')
  }, {
    name: 'SUMPRODUCT',
    intro: I18n.t('formula.sumproduct.intro'),
    usage: I18n.t('formula.sumproduct.usage'),
    example: I18n.t('formula.sumproduct.example')
  }]
}, {
  name: I18n.t('formula.textFunc'),
  children: [{
    name: 'CONCATENATE',
    intro: I18n.t('formula.concatenate.intro'),
    usage: I18n.t('formula.concatenate.usage'),
    example: I18n.t('formula.concatenate.example')
  }, {
    name: 'CHAR',
    intro: I18n.t('formula.char.intro'),
    usage: I18n.t('formula.char.usage'),
    example: I18n.t('formula.char.example')
  }, {
    name: 'EXACT',
    intro: I18n.t('formula.exact.intro'),
    usage: I18n.t('formula.exact.usage'),
    example: I18n.t('formula.exact.example')
  }, {
    name: 'GETUSERNAME',
    intro: I18n.t('formula.getusername.intro'),
    usage: I18n.t('formula.getusername.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'ISEMPTY',
    intro: I18n.t('formula.isempty.intro'),
    usage: I18n.t('formula.isempty.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'LEFT',
    intro: I18n.t('formula.left.intro'),
    usage: I18n.t('formula.left.usage'),
    example: I18n.t('formula.left.example')
  }, {
    name: 'LEN',
    intro: I18n.t('formula.len.intro'),
    usage: I18n.t('formula.len.usage'),
    example: I18n.t('formula.len.example')
  }, {
    name: 'LOWER',
    intro: I18n.t('formula.lower.intro'),
    usage: I18n.t('formula.lower.usage'),
    example: I18n.t('formula.lower.example')
  }, {
    name: 'MID',
    intro: I18n.t('formula.mid.intro'),
    usage: I18n.t('formula.mid.usage'),
    example: I18n.t('formula.mid.example')
  }, {
    name: 'REPLACE',
    intro: I18n.t('formula.replace.intro'),
    usage: I18n.t('formula.replace.usage'),
    example: I18n.t('formula.replace.example')
  }, {
    name: 'REPT',
    intro: I18n.t('formula.rept.intro'),
    usage: I18n.t('formula.rept.usage'),
    example: I18n.t('formula.rept.example')
  }, {
    name: 'RIGHT',
    intro: I18n.t('formula.right.intro'),
    usage: I18n.t('formula.right.usage'),
    example: I18n.t('formula.right.example')
  }, {
    name: 'SEARCH',
    intro: I18n.t('formula.search.intro'),
    usage: I18n.t('formula.search.usage'),
    example: I18n.t('formula.search.example')
  }, {
    name: 'SPLIT',
    intro: I18n.t('formula.split.intro'),
    usage: I18n.t('formula.split.usage'),
    example: I18n.t('formula.split.example')
  }, {
    name: 'TEXT',
    intro: I18n.t('formula.text.intro'),
    usage: I18n.t('formula.text.usage'),
    example: I18n.t('formula.text.example')
  }, {
    name: 'TRIM',
    intro: I18n.t('formula.trim.intro'),
    usage: I18n.t('formula.trim.usage'),
    example: I18n.t('formula.trim.example')
  }, {
    name: 'UPPER',
    intro: I18n.t('formula.upper.intro'),
    usage: I18n.t('formula.upper.usage'),
    example: I18n.t('formula.upper.example')
  }, {
    name: 'VALUE',
    intro: I18n.t('formula.value.intro'),
    usage: I18n.t('formula.value.usage'),
    example: I18n.t('formula.value.example')
  }]
}, {
  name: I18n.t('formula.dateFunc'),
  children: [{
    name: 'DATE',
    intro: I18n.t('formula.date.intro'),
    usage: I18n.t('formula.date.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'DATEDELTA',
    intro: I18n.t('formula.datedelta.intro'),
    usage: I18n.t('formula.datedelta.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'DAY',
    intro: I18n.t('formula.day.intro'),
    usage: I18n.t('formula.day.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'DAYS',
    intro: I18n.t('formula.days.intro'),
    usage: I18n.t('formula.days.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'DAYS360',
    intro: I18n.t('formula.days360.intro'),
    usage: I18n.t('formula.days360.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'HOUR',
    intro: I18n.t('formula.hour.intro'),
    usage: I18n.t('formula.hour.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'ISOWEEKNUM',
    intro: I18n.t('formula.isoweeknum.intro'),
    usage: I18n.t('formula.isoweeknum.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'MINUTE',
    intro: I18n.t('formula.minute.intro'),
    usage: I18n.t('formula.minute.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'MONTH',
    intro: I18n.t('formula.month.intro'),
    usage: I18n.t('formula.month.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'NOW',
    intro: I18n.t('formula.now.intro'),
    usage: I18n.t('formula.now.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'SECOND',
    intro: I18n.t('formula.second.intro'),
    usage: I18n.t('formula.second.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'SYSTIME',
    intro: I18n.t('formula.systime.intro'),
    usage: I18n.t('formula.systime.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'TIME',
    intro: I18n.t('formula.time.intro'),
    usage: I18n.t('formula.time.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'TIMESTAMP',
    intro: I18n.t('formula.timestamp.intro'),
    usage: I18n.t('formula.timestamp.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'TODAY',
    intro: I18n.t('formula.today.intro'),
    usage: I18n.t('formula.today.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'WEEKNUM',
    intro: I18n.t('formula.weeknum.intro'),
    usage: I18n.t('formula.weeknum.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'YEAR',
    intro: I18n.t('formula.year.intro'),
    usage: I18n.t('formula.year.usage'),
    example: I18n.t('formula.omit')
  }]
}, {
  name: I18n.t('formula.logicFunc'),
  children: [{
    name: 'AND',
    intro: I18n.t('formula.and.intro'),
    usage: I18n.t('formula.and.usage'),
    example: I18n.t('formula.and.example')
  }, {
    name: 'FALSE',
    intro: I18n.t('formula.false.intro'),
    usage: I18n.t('formula.false.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'IF',
    intro: I18n.t('formula.if.intro'),
    usage: I18n.t('formula.if.usage'),
    example: I18n.t('formula.if.example')
  }, {
    name: 'NOT',
    intro: I18n.t('formula.not.intro'),
    usage: I18n.t('formula.not.usage'),
    example: I18n.t('formula.not.example')
  }, {
    name: 'OR',
    intro: I18n.t('formula.or.intro'),
    usage: I18n.t('formula.or.usage'),
    example: I18n.t('formula.or.example')
  }, {
    name: 'TRUE',
    intro: I18n.t('formula.true.intro'),
    usage: I18n.t('formula.true.usage'),
    example: I18n.t('formula.omit')
  }, {
    name: 'XOR',
    intro: I18n.t('formula.xor.intro'),
    usage: I18n.t('formula.xor.usage'),
    example: I18n.t('formula.xor.example')
  }]
}, {
  name: I18n.t('formula.advanceFunc'),
  children: [{
    name: 'UUID',
    intro: I18n.t('formula.uuid.intro'),
    usage: I18n.t('formula.uuid.usage'),
    example: I18n.t('formula.omit')
  }]
}]
