export const typeOptions = [
  { value: 'start', label: '流程启动' },
  { value: 'subStart', label: '内部子流程启动' },
  { value: 'callStart', label: '外部子流程启动' },
  { value: 'end', label: '流程结束' },
  { value: 'subEnd', label: '内部子流程结束' },
  { value: 'callEnd', label: '外部子流程结束' },
  { value: 'manualEnd', label: '终止流程' },
  { value: 'agree', label: '同意' },
  { value: 'oppose', label: '反对' },
  { value: 'abandon', label: '弃权' },
  { value: 'addSign', label: '补签' },
  { value: 'reject', label: '驳回' },
  { value: 'rejectToStart', label: '驳回到发起人' },
  { value: 'rejectToPrevious', label: '驳回上一步' },
  { value: 'shfit', label: '转办' },
  { value: 'revoke', label: '撤销' },
  { value: 'suspend', label: '挂起' },
  { value: 'recover', label: '恢复' },
  { value: 'lock', label: '锁定' },
  { value: 'unlock', label: '解锁' },
  { value: 'flowImage', label: '查看流程图' },
  { value: 'flowHistory', label: '查看审批历史' },
  { value: 'saveDraft', label: '保存草稿' },
  { value: 'cleanData', label: '清除数据' },
  { value: 'manual_end', label: '删除实例' }
]
